In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
pd.DataFrame(
    {
        'a' : [4, 5, 6, 7],
        'b' : [8, 9, 10, 11],
        'c' : [12, 13, 14, 15]
    },
    index=[1, 2, 3, 4]
)

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [4]:
pd.DataFrame(
    [
        [4, 5, 6, 7],
        [8, 9, 10, 11],
        [12, 13, 14, 15]
    ],
    index=[1, 2, 3],
    columns=['a', 'b', 'c', 'd']
)

    a   b   c   d
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
# Multi-index
df = \
pd.DataFrame(
    {
        'a' : [4, 5, 6, 7],
        'b' : [8, 9, 10, 11],
        'c' : [12, 13, 14, 15]
    },
    index=pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)]
    )
)

## 데이터 정렬하기

In [7]:
df.sort_values('a', ascending=False) # 내림차순 정렬

     a   b   c
e 2  7  11  15
  1  6  10  14
d 2  5   9  13
  1  4   8  12

In [8]:
# 열 이름 변경하기
df.rename(columns={'c':'d'}) # 저장 따로 해줘야 함.

     a   b   d
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [10]:
# 인덱스 값 초기화
df.reset_index() # 저장 필요함.

  level_0  level_1  a   b   c
0       d        1  4   8  12
1       d        2  5   9  13
2       e        1  6  10  14
3       e        2  7  11  15

In [11]:
# 인덱스 순서대로 정렬하기
df.sort_index()

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [12]:
# 특정 열 제거하기
df.drop(columns=['a', 'b'])

      c
d 1  12
  2  13
e 1  14
  2  15

In [13]:
# 행 추출하기
df.head(2)

     a  b   c
d 1  4  8  12
  2  5  9  13

In [14]:
df.tail(2)

     a   b   c
e 1  6  10  14
  2  7  11  15

In [15]:
# 특정 열에 특정 값이 있을 경우 (조건 설정하기)
df[df['a'] > 4]

     a   b   c
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [16]:
df[df['a'] != 5]

     a   b   c
d 1  4   8  12
e 1  6  10  14
  2  7  11  15

In [17]:
# 특정 열에 특정 숫자가 있는지 확인하기
df[df['a'].isin([4])]

     a  b   c
d 1  4  8  12

In [18]:
# 특정 비율로 데이터 샘플링 (랜덤하게)
df.sample(frac=0.7)

     a   b   c
d 2  5   9  13
e 2  7  11  15
d 1  4   8  12

In [20]:
# 특정 개수만큼 데이터 샘플링 하기 (랜덤하게)
df.sample(n=2)

     a   b   c
e 2  7  11  15
d 2  5   9  13

In [21]:
# 특정 열에서 큰 순서대로 불러오기
df.nlargest(3, 'a')

     a   b   c
e 2  7  11  15
  1  6  10  14
d 2  5   9  13

In [22]:
# 특정 열에서 작은 순서대로 불러오기
df.nsmallest(3, 'a')

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

In [23]:
# 열 추출하기
# index 범위 설정해서 불러오기
df.iloc[1:4]

     a   b   c
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [24]:
# 첫 인덱스 지정해서 불러오기
df.iloc[2:]

     a   b   c
e 1  6  10  14
  2  7  11  15

In [25]:
# 마지막 인덱스 지정해서 불러오기
df.iloc[:3]

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

In [26]:
# 모든 인덱스 불러오기
df.iloc[:]

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [27]:
# 특정 열 지정해서 가져오기
df[['a', 'b']]

     a   b
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

In [28]:
# 조건을 만족하는 열 가져오기
df.filter(regex='c') # 정규표현식과 함께 사용된다.

      c
d 1  12
  2  13
e 1  14
  2  15

In [29]:
# 특정문자가 포함되지 않은 열 가져오기
df.filter(regex='^(?!c$).*') # ^ : 시작하다 (cf. [^] : 제외하다) / (?!c$) : 바로 뒤의 문자열이 'c'로 끝나지 않아야 한다. / .* : 어떤 문자이든지 0번 이상 반복

     a   b
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

In [ ]:
# 특정 행과 열 지정해서 가져오기

In [30]:
# index로 특정 행과 열 가져오기
df.iloc[0:3, [0, 2]]

     a   c
d 1  4  12
  2  5  13
e 1  6  14

In [31]:
# 특정 열에서 조건을 만족하는 행과 열 가져오기
df.loc[df['a'] > 5, ['a', 'c']]

     a   c
e 1  6  14
  2  7  15

In [32]:
# 인덱스 활용, 특정 조건을 만족하는 값 가져오기
df.iat[1, 2] # 첫 번째 index에서 두 번째 열 값 가져오기

13

In [34]:
# 중복 데이터 다루기
# 멀티 인덱스 생성
df = \
pd.DataFrame(
    {
        'a' : [4, 5, 6, 7, 7],
        'b' : [8, 9, 10, 11, 11],
        'c' : [12, 13, 14, 15, 15]
    },
    index=pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2), ('e', 3)]
    )
)
df

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15
  3  7  11  15

In [35]:
# 특정열에 어떤 값이 몇개 들어있는지 확인하기
df.a.value_counts()

a
7    2
4    1
5    1
6    1
Name: count, dtype: int64

In [36]:
# DF의 행이 몇 개인지 세어보기
len(df)

5

In [37]:
# DF에 행과 열이 몇 개인지 세어보기
df.shape

(5, 3)

In [39]:
# 특정 열에 unique한 값이 몇 개 있는지 세어보기
df.a.nunique()

4

In [40]:
# 데이터 프레임의 형태 한 눈에 보기 (요약 통계량)
df.describe()

             a         b         c
count  5.00000   5.00000   5.00000
mean   5.80000   9.80000  13.80000
std    1.30384   1.30384   1.30384
min    4.00000   8.00000  12.00000
25%    5.00000   9.00000  13.00000
50%    6.00000  10.00000  14.00000
75%    7.00000  11.00000  15.00000
max    7.00000  11.00000  15.00000

In [41]:
# 중복된 값 제거하기
df.drop_duplicates()

     a   b   c
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [42]:
# 데이터 파악하기
# 각 열의 합 확인하기
df.sum()

a    29
b    49
c    69
dtype: int64

In [43]:
# 각 열의 값이 모두 몇개인지 확인하기
df.count()

a    5
b    5
c    5
dtype: int64

In [44]:
# 각 열의 중앙값 확인하기 ==> 50%
df.median()

a     6.0
b    10.0
c    14.0
dtype: float64

In [45]:
# 특정 열의 평균값 확인하기
df.b.mean()

9.8

In [46]:
# 각 열의 25%, 75%에 해당하는 수 확인하기
df.quantile([0.25, 0.75])

        a     b     c
0.25  5.0   9.0  13.0
0.75  7.0  11.0  15.0

In [47]:
# 각 열의 최솟값 확인하기
df.min()

a     4
b     8
c    12
dtype: int64

In [48]:
# 각 열의 최댓값 확인하기
df.max()

a     7
b    11
c    15
dtype: int64

In [49]:
# 각 열의 표준편차 확인하기
df.std()

a    1.30384
b    1.30384
c    1.30384
dtype: float64

In [50]:
# 데이터 프레임의 각 값에 일괄적으로 특정 함수 적용하기 ==> apply() --> 이거 사용하는거 해보기 !!
df.apply(np.sqrt) # 제곱근 구하기

            a         b         c
d 1  2.000000  2.828427  3.464102
  2  2.236068  3.000000  3.605551
e 1  2.449490  3.162278  3.741657
  2  2.645751  3.316625  3.872983
  3  2.645751  3.316625  3.872983

## 결측치 다루기

In [52]:
# 멀티 인덱스 생성
df = \
pd.DataFrame(
    {
        'a' : [4, 5, 6, np.nan],
        'b' : [7, 8, np.nan, 9],
        'c' : [12, np.nan, 15, 16]
    },
    index=pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)]
    )
)
df

       a    b     c
d 1  4.0  7.0  12.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  15.0
  2  NaN  9.0  16.0

In [53]:
# null값 확인하기
df.isnull().sum()

a    1
b    1
c    1
dtype: int64

In [54]:
pd.notnull(df)

         a      b      c
d 1   True   True   True
  2   True   True  False
e 1   True  False   True
  2  False   True   True

In [55]:
# null 값이 있는 행 삭제하기
df.dropna()

       a    b     c
d 1  4.0  7.0  12.0

In [56]:
# null값을 특정 값으로 대체하기
df.fillna(0)

       a    b     c
d 1  4.0  7.0  12.0
  2  5.0  8.0   0.0
e 1  6.0  0.0  15.0
  2  0.0  9.0  16.0

In [57]:
# null값을 특정 계산 결과 대체하기
# 평균값으로 대체하기
df.a.mean()

5.0

In [58]:
df.fillna(df.a.mean())

       a    b     c
d 1  4.0  7.0  12.0
  2  5.0  8.0   5.0
e 1  6.0  5.0  15.0
  2  5.0  9.0  16.0

## 새로운 열 만들기

In [59]:
# 멀티 인덱스 생성
df = \
pd.DataFrame(
    {
        'a' : [4, 5, 6, 7],
        'b' : [7, 8, 9, 10],
        'c' : [12, 13, 15, 16]
    },
    index=pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)]
    )
)
df

     a   b   c
d 1  4   7  12
  2  5   8  13
e 1  6   9  15
  2  7  10  16

In [61]:
# 조건에 맞는 새로운 열 만들기
df['Sum'] = df.a + df.b + df.c
df

     a   b   c  Sum
d 1  4   7  12   23
  2  5   8  13   26
e 1  6   9  15   30
  2  7  10  16   33

In [62]:
# assign() 이용, 조건에 맞는 새로운 열 만들기
# a, b, c열 값을 모두 더해서 d열 생성하기
df = df.assign(multiply=lambda df : df.a * df.b * df.c)
df

     a   b   c  Sum  multiply
d 1  4   7  12   23       336
  2  5   8  13   26       520
e 1  6   9  15   30       810
  2  7  10  16   33      1120

In [64]:
# 숫자형 데이터를 구간 나누기
# a열을 두개로 나누어 각각 새롭게 레이블을 만드는 방법
df['Qcut'] = pd.qcut(df.a, 2, labels=['600 이하', '600 이상'])
df

     a   b   c  Sum  multiply    Qcut
d 1  4   7  12   23       336  600 이하
  2  5   8  13   26       520  600 이하
e 1  6   9  15   30       810  600 이상
  2  7  10  16   33      1120  600 이상

In [65]:
# 기준 값 이하와 이상을 모두 통일 시키기
# a열에서 5 이하는 모두 5로, 6 이상은 모두 6으로 변환
df['Clip'] = df.a.clip(lower=5, upper=6)
df

     a   b   c  Sum  multiply    Qcut  Clip
d 1  4   7  12   23       336  600 이하     5
  2  5   8  13   26       520  600 이하     5
e 1  6   9  15   30       810  600 이상     6
  2  7  10  16   33      1120  600 이상     6

In [66]:
# 최댓값 불러오기
df.max(axis=0) # 서로 다른 행과 행을 비교하기 (열 방향)
# df.max(axis=1) : 행 방향

a                7
b               10
c               16
Sum             33
multiply      1120
Qcut        600 이상
Clip             6
dtype: object

In [68]:
df.drop(columns='Qcut').max(axis=1)

d  1     336
   2     520
e  1     810
   2    1120
dtype: int64

In [69]:
df.min(axis=0)

a                4
b                7
c               12
Sum             23
multiply       336
Qcut        600 이하
Clip             5
dtype: object

In [71]:
# 행과 열 변환
df = \
pd.DataFrame({'A' : {0:'a', 1:'b', 2:'c'},
              'B' : {0:1, 1:3, 2:5},
              'C' : {0:2, 1:4, 2:6}
             })
df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

* melt ==> 연습하기

In [72]:
df.melt()

  variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

In [73]:
# 하나의 열만 행으로 이동시키기
pd.melt(df, id_vars=['A'], value_vars=['B']) # A열만 그대로, B열은 행으로 이동

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [75]:
# 여러 개 열을 행으로 이동시키기
# A열은 고정, 나머지 B와 C열은 행으로 이동
df_melt = df.melt(id_vars=['A'], value_vars=['B', 'C'])
df_melt

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

* pivot 연습 !

In [77]:
# 특정 열의 값을 기준, 새로운 열 만들기
df_pivot = df_melt.pivot(index='A', columns='variable', values='value')
df_pivot

variable  B  C
A
a         1  2
b         3  4
c         5  6

In [79]:
# 원래의 데이터 형태로 복원하기
df_origin = df_pivot.reset_index()
df_origin.columns.name = None
df_origin

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [81]:
# Series로 데이터 연결하기
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

pd.concat([s1, s2], ignore_index=True)

0    a
1    b
2    c
3    d
dtype: object

In [82]:
# 계층적 인덱스 추가, 열 이름 지정
pd.concat([s1, s2],
          keys=['s1', 's2'],
          names=['Series name', 'Row index'])

Series name  Row index
s1           0            a
             1            b
s2           0            c
             1            d
dtype: object

## 데이터프레임 연결하기
* merge(), concat()

In [86]:
df1 = \
pd.DataFrame([['a', 1],
              ['b', 2]],
             columns=['letter', 'number'])

df2 = \
pd.DataFrame([['c', 3],
              ['e', 4]],
             columns=['letter', 'number'])

In [84]:
df3 = \
pd.DataFrame([['c', 3, 'cat'],
              ['d', 4, 'dog']],
             columns=['letter', 'number', 'animal'])

df4 = \
pd.DataFrame([['bird', 'polly'],
              ['monkey', 'george']],
             columns=['animal', 'name'])

In [87]:
# 데이터 프레임 합치기
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      e       4

In [88]:
pd.concat([df1, df3]) # axis=0 (default)

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [89]:
pd.concat([df1, df3], axis=1)

  letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [90]:
# 함께 공유하는 열만 합치기
pd.concat([df1, df3], join='inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [91]:
# merge()
pd.merge(df2, df3, how='left', on='number') # 왼쪽 df로

  letter_x  number letter_y animal
0        c       3        c    cat
1        e       4        d    dog

In [92]:
pd.merge(df2, df3, how='right', on='number') # 오른쪽 df로

  letter_x  number letter_y animal
0        c       3        c    cat
1        e       4        d    dog

In [93]:
# outer
pd.merge(df2, df3, how='outer', on='number')

  letter_x  number letter_y animal
0        c       3        c    cat
1        e       4        d    dog

In [94]:
# 특정 열 비교, 공통값이 존재하는 경우만 추출
df2[df2.letter.isin(df3.letter)]

  letter  number
0      c       3

In [95]:
df2[~df2.letter.isin(df3.letter)]

  letter  number
1      e       4

In [96]:
# 공통값이 있는 것만 병합
pd.merge(df2, df3)

  letter  number animal
0      c       3    cat

In [97]:
# 어디서 병합되었는지 source 표시하기
pd.merge(df2, df3, how='outer', indicator=True)

  letter  number animal      _merge
0      c       3    cat        both
1      e       4    NaN   left_only
2      d       4    dog  right_only

In [98]:
# 원하는 병합만 남기기
pd.merge(df2, df3, how='outer', indicator=True).query('_merge == "left_only"')

  letter  number animal     _merge
1      e       4    NaN  left_only

In [99]:
# merge 컬럼 없애기
pd.merge(df2, df3, how='outer', indicator=True).query('_merge == "left_only"').drop(columns=['_merge'])

  letter  number animal
1      e       4    NaN

## 데이터 가공하기

In [101]:
df = \
pd.DataFrame(
    {
        'a' : [4, 5, 6, 7],
        'b' : [8, 9, 10, 11],
        'c' : [12, 13, 14, 15]
    },
    index=[1, 2, 3, 4]
)
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [102]:
# 행 전체를 한 칸 아래로 이동하기
df.shift(1)

     a     b     c
1  NaN   NaN   NaN
2  4.0   8.0  12.0
3  5.0   9.0  13.0
4  6.0  10.0  14.0

In [103]:
df.cumsum()

    a   b   c
1   4   8  12
2   9  17  25
3  15  27  39
4  22  38  54

In [104]:
df.cummax()

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [105]:
df.cummin()

   a  b   c
1  4  8  12
2  4  8  12
3  4  8  12
4  4  8  12

In [106]:
df.cumprod()

     a     b      c
1    4     8     12
2   20    72    156
3  120   720   2184
4  840  7920  32760

In [108]:
# 그룹별 집계하기
!git clone http://github.com/taehojo/data.git

Cloning into 'data'...
warning: redirecting to https://github.com/taehojo/data.git/

In [109]:
raw = pd.read_csv('./data/house_train.csv')
df = raw.copy()
print(df.shape)
df.head(2)

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [110]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [112]:
# 그룹 지정, 그룹별 데이터 수 표시
df.groupby(by='YrSold').size()

YrSold
2006    314
2007    329
2008    304
2009    338
2010    175
dtype: int64

In [113]:
# 그룹 지정 후 원하는 컬럼 표시
# 각 그룹별 팔린 연도별 주차장 넓이 표시하기
df.groupby(by='YrSold')['LotArea'].mean()

YrSold
2006    10489.458599
2007    10863.686930
2008    10587.687500
2009    10294.248521
2010    10220.645714
Name: LotArea, dtype: float64

In [115]:
# 그룹별 집계
# 밀집도 기준, 순위 부여
df.SalePrice.rank(method='dense')

0       413.0
1       340.0
2       443.0
3       195.0
4       495.0
        ...
1455    315.0
1456    416.0
1457    528.0
1458    200.0
1459    222.0
Name: SalePrice, Length: 1460, dtype: float64

In [116]:
# 최저값 기준, 순위 부여
df.SalePrice.rank(method='min')

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     828.0
1456    1076.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64

In [117]:
# 순위를 비율로 표시하기
# 집 값의 순위 비율 표시 (0:가장 싼 집, 1:가장 비싼 집)
df.SalePrice.rank(pct=True)

0       0.734247
1       0.622603
2       0.777740
3       0.342123
4       0.848973
          ...
1455    0.569863
1456    0.738356
1457    0.880137
1458    0.358904
1459    0.404795
Name: SalePrice, Length: 1460, dtype: float64

In [118]:
# 동일 순위에 대한 처리 방법 정하기
df.SalePrice.rank(method='first') # 순서가 가장 빠른 사람을 상위로 처리

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     836.0
1456    1080.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64